import { jsPDF } from 'jspdf'

interface CreativeReference {
  title: string
  description: string
  imageBase64: string | null
  style: string
  platform: string
}

export async function generateAdIntelligencePDF(
  reportMarkdown: string,
  companyName: string,
  creativeReferences: CreativeReference[] = []
): Promise<Blob> {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentWidth = pageWidth - margin * 2
  let y = margin

  const colors = {
    primary: [14, 165, 233] as [number, number, number],
    heading: [30, 41, 59] as [number, number, number],
    text: [51, 65, 85] as [number, number, number],
    subtle: [100, 116, 139] as [number, number, number],
    accent: [139, 92, 246] as [number, number, number],
    red: [239, 68, 68] as [number, number, number],
    green: [34, 197, 94] as [number, number, number],
  }

  const addFooter = () => {
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.setTextColor(...colors.subtle)
    doc.text(
      'Generated by Genome AI - Ad Intelligence Engine',
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    )
  }

  const checkPage = (needed: number = 15) => {
    if (y > pageHeight - needed) {
      addFooter()
      doc.addPage()
      y = margin
    }
  }

  // Parse and render the markdown report
  const lines = reportMarkdown.split('\n')

  for (const line of lines) {
    const trimmed = line.trim()

    if (!trimmed) {
      y += 3
      continue
    }

    if (trimmed === '---' || trimmed === '***') {
      checkPage(10)
      y += 4
      doc.setDrawColor(...colors.subtle)
      doc.setLineWidth(0.3)
      doc.line(margin, y, pageWidth - margin, y)
      y += 6
      continue
    }

    if (trimmed.startsWith('# ')) {
      checkPage(25)
      y += 6
      doc.setFontSize(22)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...colors.primary)
      const text = trimmed.replace(/^#\s+/, '').replace(/\*\*/g, '')
      const wrapped = doc.splitTextToSize(text, contentWidth)
      doc.text(wrapped, margin, y)
      y += wrapped.length * 10 + 4
      continue
    }

    if (trimmed.startsWith('## ')) {
      checkPage(20)
      y += 8
      doc.setFontSize(16)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...colors.primary)
      const text = trimmed.replace(/^##\s+/, '').replace(/\*\*/g, '')
      const wrapped = doc.splitTextToSize(text, contentWidth)
      doc.text(wrapped, margin, y)
      y += wrapped.length * 8 + 3
      doc.setDrawColor(...colors.primary)
      doc.setLineWidth(0.5)
      doc.line(margin, y, margin + 50, y)
      y += 5
      continue
    }

    if (trimmed.startsWith('### ')) {
      checkPage(18)
      y += 5
      doc.setFontSize(13)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...colors.accent)
      const text = trimmed.replace(/^###\s+/, '').replace(/\*\*/g, '')
      const wrapped = doc.splitTextToSize(text, contentWidth)
      doc.text(wrapped, margin, y)
      y += wrapped.length * 7 + 3
      continue
    }

    if (trimmed.startsWith('**') && trimmed.includes('**:')) {
      checkPage(12)
      doc.setFontSize(10)
      const boldMatch = trimmed.match(/^\*\*(.+?)\*\*:\s*(.*)$/)
      if (boldMatch) {
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(...colors.heading)
        const label = boldMatch[1] + ': '
        const labelWidth = doc.getTextWidth(label)
        doc.text(label, margin + 5, y)

        doc.setFont('helvetica', 'normal')
        doc.setTextColor(...colors.text)
        const value = boldMatch[2]
        const wrapped = doc.splitTextToSize(value, contentWidth - labelWidth - 10)
        doc.text(wrapped, margin + 5 + labelWidth, y)
        y += Math.max(wrapped.length, 1) * 5 + 2
      } else {
        const clean = trimmed.replace(/\*\*/g, '')
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(...colors.text)
        const wrapped = doc.splitTextToSize(clean, contentWidth)
        doc.text(wrapped, margin, y)
        y += wrapped.length * 5 + 2
      }
      continue
    }

    if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      checkPage(12)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...colors.text)
      const text = trimmed.replace(/^[-*]\s+/, '').replace(/\*\*/g, '')
      const wrapped = doc.splitTextToSize(text, contentWidth - 15)

      doc.setFillColor(...colors.primary)
      doc.circle(margin + 4, y - 1.5, 1, 'F')

      doc.text(wrapped, margin + 10, y)
      y += wrapped.length * 5 + 2
      continue
    }

    if (trimmed.startsWith('**') && trimmed.endsWith('**')) {
      checkPage(12)
      doc.setFontSize(11)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...colors.heading)
      const text = trimmed.replace(/\*\*/g, '')
      const wrapped = doc.splitTextToSize(text, contentWidth)
      doc.text(wrapped, margin, y)
      y += wrapped.length * 6 + 2
      continue
    }

    if (trimmed.startsWith('*') && trimmed.endsWith('*') && !trimmed.startsWith('**')) {
      checkPage(10)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'italic')
      doc.setTextColor(...colors.subtle)
      const text = trimmed.replace(/^\*|\*$/g, '')
      const wrapped = doc.splitTextToSize(text, contentWidth)
      doc.text(wrapped, margin, y)
      y += wrapped.length * 5 + 2
      continue
    }

    checkPage(12)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...colors.text)
    const clean = trimmed.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1')
    const wrapped = doc.splitTextToSize(clean, contentWidth)
    doc.text(wrapped, margin, y)
    y += wrapped.length * 5 + 2
  }

  // Add Creative Reference Images section
  if (creativeReferences.length > 0) {
    addFooter()
    doc.addPage()
    y = margin

    // Section title
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...colors.primary)
    doc.text('Creative Ad References', margin, y)
    y += 10

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...colors.subtle)
    doc.text('AI-generated creative concepts tailored for your brand', margin, y)
    y += 8

    doc.setDrawColor(...colors.primary)
    doc.setLineWidth(0.5)
    doc.line(margin, y, margin + 60, y)
    y += 10

    for (let i = 0; i < creativeReferences.length; i++) {
      const ref = creativeReferences[i]
      const imgWidth = contentWidth * 0.6
      const imgHeight = imgWidth

      checkPage(imgHeight + 40)

      // Title
      doc.setFontSize(14)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...colors.accent)
      doc.text(`${i + 1}. ${ref.title}`, margin, y)

      // Platform & Style badges
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...colors.primary)
      const titleWidth = doc.getTextWidth(`${i + 1}. ${ref.title}  `)
      doc.setFontSize(8)
      const badgeText = `${ref.platform} | ${ref.style}`
      doc.text(badgeText, margin + titleWidth + 5, y)
      y += 8

      // Image centered
      const imgX = margin + (contentWidth - imgWidth) / 2
      if (ref.imageBase64) {
        try {
          doc.addImage(ref.imageBase64, 'PNG', imgX, y, imgWidth, imgHeight)
        } catch {
          doc.setDrawColor(...colors.subtle)
          doc.setFillColor(241, 245, 249)
          doc.roundedRect(imgX, y, imgWidth, imgHeight, 3, 3, 'FD')
          doc.setFontSize(10)
          doc.setTextColor(...colors.subtle)
          doc.text('Image unavailable', imgX + imgWidth / 2, y + imgHeight / 2, { align: 'center' })
        }
      } else {
        doc.setDrawColor(...colors.subtle)
        doc.setFillColor(241, 245, 249)
        doc.roundedRect(imgX, y, imgWidth, imgHeight, 3, 3, 'FD')
        doc.setFontSize(10)
        doc.setTextColor(...colors.subtle)
        doc.text('Image unavailable', imgX + imgWidth / 2, y + imgHeight / 2, { align: 'center' })
      }

      y += imgHeight + 5

      // Description
      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...colors.text)
      const desc = doc.splitTextToSize(ref.description || '', contentWidth)
      doc.text(desc, margin, y)
      y += desc.length * 4 + 10

      // Separator
      if (i < creativeReferences.length - 1) {
        doc.setDrawColor(...colors.subtle)
        doc.setLineWidth(0.2)
        doc.line(margin, y, pageWidth - margin, y)
        y += 8
      }
    }
  }

  // Final footer
  addFooter()

  return doc.output('blob') as unknown as Blob
}
